### ISSUE TITLE
make_qr() function is not exposed in package

### ISSUE THREAD

**Issue by jmcastagnetto** [mrjoh3/ggtrack#15]
Although the function `make_qr()` is documented in https://mrjoh3.github.io/ggtrack/reference/make_qr.html, and defined in https://github.com/mrjoh3/ggtrack/blob/86d401c1008ab088a926f55ba20507cfe42f5eb6/R/qr.R#L87, it is not exported in the package.

**Comment by mrjoh3** [comment]
not sure about this `make_qr` is intended to be a low-level function that only returns a matrix of colors. There is not much you can do with this but `add_qr` processes it into a raster for display

**Comment by jmcastagnetto** [comment]
Sorry for the delay in commenting. Indeed, most of the important work is done in `add_qr()`. This internal function should not be documented. Will close this and the associated PR.
