### ISSUE TITLE
Enhancemente: Git ref and timestamp should be optional

### ISSUE THREAD

**Issue by jmcastagnetto** [mrjoh3/ggtrack#16]
At the line:

https://github.com/mrjoh3/ggtrack/blob/86d401c1008ab088a926f55ba20507cfe42f5eb6/R/qr.R#L98

Adding the git hash and/or the timestamp should be optional, in that way, for example, the QR can encode the URL to download a full report from which the image shown is just a  part or example.

**Comment by mrjoh3** [comment]
using `add_qr` you can add any content to be encoded. Have a look at https://mrjoh3.github.io/ggtrack/articles/ggtrack.html#using-ggtrack . 

The git stamp and timestamp get added to the end of this free text. To me Including the source and time is an essential element of the package

**Comment by jmcastagnetto** [comment]
OK, I grok that now. Will close this issue
